"""ForgeTestCells.esp: three small generated test cells for quick-boot playtests.

  arena   ForgeTestArena  interior, lit, walled 2048 x 2048: spells and combat. An essential
          target dummy (ForgeArenaDummyRef) that never fights back, a passive spell caster
          (ForgeArenaCasterRef: scripted `cast` steps use it), cover blocks, a spawn marker.
  street  ForgeTestStreet behaves like an exterior (sky, weather, day/night): two rows of walls,
          a merchant with a work/evening schedule, two townsfolk, and a load door to the arena.
  open    ForgeTestOpen   behaves like an exterior, 4096 x 4096 open floor: weather and
          projectiles. A dummy at 1500 units and cover blocks at several ranges.

Everything is new records (no vanilla record is overridden). Vanilla references are limited to
engine-fixed FormIDs: Oblivion.esm's Imperial race (0x00000907), Gold001 (0x0000000F) and the
XMarkerHeading static (0x00000034). The geometry is a small mesh kit generated by assetkit
(meshes\\forge\\testcells\\*.nif), staged into the test game only for the run.

"Exterior" cells are interiors flagged "behave like exterior": Oblivion shows sky and weather in
them and `fw <weather>` works, without a worldspace, landscape or LOD. A real worldspace patch is
a Track G job.

A layout (cells, refs, NPC packages and schedules, kit sizes) is returned with the bytes and
saved next to the plugin as ForgeTestCells.layout.json; `forge preview` and the manifest use it.
"""

from __future__ import annotations

import json
import math
import struct
from pathlib import Path

from .esp import PluginWriter, f32, pos, u8, u32, zs

PLUGIN_NAME = "ForgeTestCells.esp"
MASTERS = ["Oblivion.esm"]

# engine-fixed vanilla FormIDs (master index 0 = Oblivion.esm)
IMPERIAL_RACE = 0x00000907
GOLD001 = 0x0000000F
XMARKER_HEADING = 0x00000034
SKELETON = "Characters\\_Male\\skeleton.nif"

# mesh kit: size in game units (x, y, z); origin at the bottom centre unless noted
KIT = {
    "floor":   {"size": (1024, 1024, 16), "origin": "top", "texture": "stone", "edid": "ForgeKitFloor"},
    "wall":    {"size": (1024, 32, 384), "origin": "bottom", "texture": "stone", "edid": "ForgeKitWall"},
    "block":   {"size": (128, 128, 128), "origin": "bottom", "texture": "wood", "edid": "ForgeKitBlock"},
    "door":    {"size": (128, 16, 224), "origin": "bottom", "texture": "wood", "edid": "ForgeKitDoor"},
    "trinket": {"size": (12, 12, 12), "origin": "bottom", "texture": "wood", "edid": "ForgeTestTrinket"},
}
KIT_MESH_DIR = "forge\\testcells"           # under Data\meshes\
KIT_TEX_DIR = "forge\\testcells"            # under Data\textures\

CELLS = {
    "arena": {"edid": "ForgeTestArena", "name": "Forge Test Arena", "start": "ForgeArenaStartRef",
              "exterior": False, "half": (1024, 1024)},
    "street": {"edid": "ForgeTestStreet", "name": "Forge Test Street", "start": "ForgeStreetStartRef",
               "exterior": True, "half": (512, 1536)},
    "open": {"edid": "ForgeTestOpen", "name": "Forge Test Grounds", "start": "ForgeOpenStartRef",
             "exterior": True, "half": (2048, 2048)},
}
DEFAULT_CELL = "arena"

# Actor value codes for skills (CLAS major skills)
SKILLS = ["Armorer", "Athletics", "Blade", "Block", "Blunt", "HandToHand", "HeavyArmor", "Alchemy", "Alteration",
          "Conjuration", "Destruction", "Illusion", "Mysticism", "Restoration", "Acrobatics", "LightArmor",
          "Marksman", "Mercantile", "Security", "Sneak", "Speechcraft"]
SKILL_AV = {n: 12 + i for i, n in enumerate(SKILLS)}

# AIDT service flags
SERVICES = {"weapons": 0x1, "armor": 0x2, "clothing": 0x4, "books": 0x8, "ingredients": 0x10, "lights": 0x80,
            "apparatus": 0x100, "misc": 0x400, "spells": 0x800, "magic_items": 0x1000, "potions": 0x2000,
            "training": 0x4000, "recharge": 0x10000, "repair": 0x20000}
PACKAGE_TYPES = {"find": 0, "follow": 1, "escort": 2, "eat": 3, "sleep": 4, "wander": 5, "travel": 6,
                 "accompany": 7, "useitemat": 8, "ambush": 9, "flee": 10, "castmagic": 11}
LOCATION_TYPES = {"near_ref": 0, "in_cell": 1, "near_current": 2, "near_editor": 3}


def _bounds_radius(key: str) -> float:
    sx, sy, sz = KIT[key]["size"]
    return round(math.sqrt((sx / 2) ** 2 + (sy / 2) ** 2 + (sz / 2) ** 2), 2)


def kit_mesh(key: str) -> str:
    return f"{KIT_MESH_DIR}\\{key}.nif"


# ---------------------------------------------------------------- layout (pure data)
def _floor(cx: float, cy: float, nx: int, ny: int) -> list[dict]:
    tiles = []
    for i in range(nx):
        for j in range(ny):
            x = cx + (i - (nx - 1) / 2) * 1024
            y = cy + (j - (ny - 1) / 2) * 1024
            tiles.append({"base": "floor", "pos": [x, y, 0.0], "rot": 0.0})
    return tiles


def _walls(hx: float, hy: float, gaps: tuple = ()) -> list[dict]:
    """Walls around a rectangle (half sizes hx, hy); gaps = list of (side, centre) to leave open."""
    out = []
    for side in ("n", "s", "e", "w"):
        length = 2 * (hx if side in "ns" else hy)
        for k in range(int(length // 1024)):
            c = -length / 2 + 512 + k * 1024
            if (side, c) in gaps:
                continue
            if side == "n":
                out.append({"base": "wall", "pos": [c, hy, 0.0], "rot": 0.0})
            elif side == "s":
                out.append({"base": "wall", "pos": [c, -hy, 0.0], "rot": 0.0})
            elif side == "e":
                out.append({"base": "wall", "pos": [hx, c, 0.0], "rot": math.pi / 2})
            else:
                out.append({"base": "wall", "pos": [-hx, c, 0.0], "rot": math.pi / 2})
    return out


def layout() -> dict:
    """The full description of the test cells; the plugin, preview and manifest all come from this."""
    npcs = {
        "ForgeArenaDummy": {"name": "Training Dummy", "level": 10, "health": 500, "essential": True,
                            "aggression": 0, "confidence": 100, "packages": ["ForgeStayPkg"],
                            "skills": 10, "attributes": 40},
        "ForgeArenaCaster": {"name": "Spell Tester", "level": 10, "health": 500, "essential": True,
                             "aggression": 0, "confidence": 100, "packages": ["ForgeStayPkg"],
                             "skills": 50, "attributes": 60},
        "ForgeStreetMerchant": {"name": "Ilvia the Trader", "level": 8, "health": 120, "essential": True,
                                "aggression": 5, "confidence": 50, "barter_gold": 800,
                                "services": ["weapons", "armor", "misc", "potions"],
                                "packages": ["ForgeMerchantWorkPkg", "ForgeMerchantEveningPkg"],
                                "items": [["ForgeTestTrinket", 10], ["Gold001", 50]],
                                "skills": 25, "attributes": 45, "mercantile": 60},
        "ForgeStreetTownsfolk": {"name": "Townsperson", "level": 3, "health": 60, "essential": True,
                                 "aggression": 5, "confidence": 30, "packages": ["ForgeTownsfolkWanderPkg"],
                                 "skills": 15, "attributes": 40},
    }
    packages = {
        "ForgeStayPkg": {"type": "wander", "location": ["near_editor", None, 32], "hour": 0, "duration": 24,
                         "flags": 0, "note": "stand at the editor spot all day"},
        "ForgeMerchantWorkPkg": {"type": "wander", "location": ["near_ref", "ForgeStreetStallRef", 256],
                                 "hour": 8, "duration": 12, "flags": 0x1,
                                 "note": "08:00-20:00 work the stall, offers barter"},
        "ForgeMerchantEveningPkg": {"type": "travel", "location": ["near_ref", "ForgeStreetHomeRef", 64],
                                    "hour": 20, "duration": 12, "flags": 0,
                                    "note": "20:00-08:00 walk to the house door and stay there"},
        "ForgeTownsfolkWanderPkg": {"type": "wander", "location": ["in_cell", "ForgeTestStreet", 1024],
                                    "hour": 0, "duration": 24, "flags": 0,
                                    "note": "wander the street all day"},
    }
    arena = _floor(0, 0, 2, 2) + _walls(1024, 1024, gaps=(("s", -512.0),))
    arena += [{"base": "block", "pos": [x, y, 0.0], "rot": 0.0} for x, y in ((-512, 0), (512, 0), (0, -256))]
    arena += [
        {"base": "marker", "pos": [0, -768, 0], "rot": 0.0, "edid": "ForgeArenaStartRef", "persistent": True},
        {"base": "marker", "pos": [384, 256, 0], "rot": math.pi, "edid": "ForgeArenaSpawnRef", "persistent": True},
        {"base": "npc:ForgeArenaDummy", "pos": [0, 512, 0], "rot": math.pi, "edid": "ForgeArenaDummyRef",
         "persistent": True},
        {"base": "npc:ForgeArenaCaster", "pos": [256, -400, 0], "rot": 0.0, "edid": "ForgeArenaCasterRef",
         "persistent": True},
        {"base": "door", "pos": [-512, -1016, 0], "rot": 0.0, "edid": "ForgeArenaDoorRef", "persistent": True,
         "teleport": {"to": "ForgeStreetDoorRef", "pos": [0, 1380, 0], "rot": math.pi}},
    ]
    street = _floor(0, 0, 1, 3) + _walls(512, 1536)
    street += [{"base": "block", "pos": [x, y, 0.0], "rot": 0.0} for x, y in ((-384, -900), (-384, -772), (384, 300))]
    street += [
        {"base": "marker", "pos": [0, -1300, 0], "rot": 0.0, "edid": "ForgeStreetStartRef", "persistent": True},
        {"base": "marker", "pos": [-300, -836, 0], "rot": math.pi / 2, "edid": "ForgeStreetStallRef",
         "persistent": True},
        {"base": "marker", "pos": [300, 1200, 0], "rot": 0.0, "edid": "ForgeStreetHomeRef", "persistent": True},
        {"base": "npc:ForgeStreetMerchant", "pos": [-250, -836, 0], "rot": -math.pi / 2,
         "edid": "ForgeStreetMerchantRef", "persistent": True},
        {"base": "npc:ForgeStreetTownsfolk", "pos": [200, -200, 0], "rot": math.pi, "edid": "ForgeStreetTownsfolkRef",
         "persistent": True},
        {"base": "npc:ForgeStreetTownsfolk", "pos": [-150, 600, 0], "rot": 0.0, "edid": "ForgeStreetTownsfolk2Ref",
         "persistent": True},
        {"base": "door", "pos": [0, 1520, 0], "rot": math.pi, "edid": "ForgeStreetDoorRef", "persistent": True,
         "teleport": {"to": "ForgeArenaDoorRef", "pos": [-512, -880, 0], "rot": 0.0}},
        {"base": "door", "pos": [496, 1200, 0], "rot": math.pi / 2, "edid": "ForgeStreetHouseDoorRef",
         "persistent": False},
    ]
    open_ = _floor(0, 0, 4, 4)
    open_ += [{"base": "block", "pos": [x, y, 0.0], "rot": 0.0} for x, y in ((0, 500), (-600, 1000), (600, 1000), (0, 1800))]
    open_ += [
        {"base": "marker", "pos": [0, -1500, 0], "rot": 0.0, "edid": "ForgeOpenStartRef", "persistent": True},
        {"base": "npc:ForgeArenaDummy", "pos": [0, 1500, 0], "rot": math.pi, "edid": "ForgeOpenDummyRef",
         "persistent": True},
    ]
    return {
        "plugin": PLUGIN_NAME, "masters": MASTERS,
        "kit": {k: {"size": list(v["size"]), "origin": v["origin"], "edid": v["edid"], "mesh": kit_mesh(k)}
                for k, v in KIT.items()},
        "cells": {key: {**meta, "refs": {"arena": arena, "street": street, "open": open_}[key]}
                  for key, meta in CELLS.items()},
        "npcs": npcs, "packages": packages,
    }


# ---------------------------------------------------------------- records
def _xcll(ambient=(150, 145, 140), directional=(255, 245, 225), fog=(30, 30, 35)) -> bytes:
    return (bytes([*ambient, 0]) + bytes([*directional, 0]) + bytes([*fog, 0])
            + struct.pack("<ffiiff", 2000.0, 12000.0, 45, 60, 1.0, 20000.0))


def _clas(w: PluginWriter) -> int:
    r = w.record("CLAS", "ForgeTestClass")
    r.add("FULL", zs("Test Subject"))
    major = [SKILL_AV[s] for s in ("Blade", "Block", "Blunt", "HeavyArmor", "Athletics", "Destruction", "Mercantile")]
    r.add("DATA", struct.pack("<2iI7iIIbB2x", 0, 1, 0, *major, 0, 0, 0, 0))
    return r.fid


def _npc(w: PluginWriter, edid: str, d: dict, class_fid: int, pkg_fids: dict, form_fid) -> None:
    r = w.record("NPC_", edid)
    r.add("FULL", zs(d["name"]))
    r.add("MODL", zs(SKELETON))
    flags = 0x02 if d.get("essential") else 0
    r.add("ACBS", struct.pack("<IHHHhHH", flags, 0, 0, d.get("barter_gold", 0), d["level"], 0, 0))
    r.add("RNAM", u32(IMPERIAL_RACE))
    for item, count in d.get("items", []):
        r.add("CNTO", struct.pack("<Ii", form_fid(item), count))
    services = 0
    for s in d.get("services", []):
        services |= SERVICES[s]
    r.add("AIDT", struct.pack("<BBBBIbBH", d["aggression"], d["confidence"], 50, 50, services, -1, 0, 0))
    for p in d.get("packages", []):
        r.add("PKID", u32(pkg_fids[p]))
    r.add("CNAM", u32(class_fid))
    skills = [d.get("skills", 10)] * 21
    if "mercantile" in d:
        skills[SKILLS.index("Mercantile")] = d["mercantile"]
    r.add("DATA", bytes(skills) + struct.pack("<I", d["health"]) + bytes([d.get("attributes", 40)] * 8))


def _package(w: PluginWriter, edid: str, p: dict, ref_fid) -> int:
    r = w.record("PACK", edid)
    r.add("PKDT", struct.pack("<IB3x", p["flags"], PACKAGE_TYPES[p["type"]]))
    ltype, target, radius = p["location"]
    r.add("PLDT", struct.pack("<iIi", LOCATION_TYPES[ltype], ref_fid(target) if target else 0, radius))
    r.add("PSDT", struct.pack("<bbBbi", -1, -1, 0, p["hour"], p["duration"]))
    return r.fid


def build_plugin(lay: dict | None = None) -> tuple[bytes, dict]:
    """Return (plugin bytes, layout with resolved FormIDs). Deterministic."""
    lay = json.loads(json.dumps(lay or layout()))
    w = PluginWriter(MASTERS, author="TES4Forge playtest",
                     desc="Generated test cells for forge playtest. Test profile only; never install for play.")
    class_fid = _clas(w)
    # kit bases
    for key, k in KIT.items():
        if key == "door":
            r = w.record("DOOR", k["edid"])
            r.add("FULL", zs("Door"))
            r.add("MODL", zs(kit_mesh(key)))
            r.add("MODB", f32(_bounds_radius(key)))
            r.add("DATA", u8(0))
        elif key == "trinket":
            r = w.record("MISC", k["edid"])
            r.add("FULL", zs("Test Trinket"))
            r.add("MODL", zs(kit_mesh(key)))
            r.add("MODB", f32(_bounds_radius(key)))
            r.add("DATA", struct.pack("<if", 5, 0.5))
        else:
            r = w.record("STAT", k["edid"])
            r.add("MODL", zs(kit_mesh(key)))
            r.add("MODB", f32(_bounds_radius(key)))
    # cells first (so refs get FormIDs before packages resolve them)
    cell_objs = {}
    for key, c in lay["cells"].items():
        cell = w.cell(c["edid"])
        cell.rec.add("FULL", zs(c["name"]))
        cell.rec.add("DATA", u8(0x01 | (0x80 if c["exterior"] else 0)))
        if not c["exterior"]:
            cell.rec.add("XCLL", _xcll())
        cell_objs[key] = cell
    # persistent / named refs get FormIDs before the NPC and package records point at them
    ref_recs = {}
    for key, c in lay["cells"].items():
        for i, ref in enumerate(c["refs"]):
            sig = "ACHR" if ref["base"].startswith("npc:") else "REFR"
            r = w.ref(cell_objs[key], sig, ref.get("edid"), ref.get("persistent", False))
            ref_recs[(key, i)] = r
            ref["formid"] = f"{r.fid:08X}"
    pkg_fids = {}

    def ref_fid(name: str) -> int:
        return w.fid(name)

    for edid, p in lay["packages"].items():
        pkg_fids[edid] = _package(w, edid, p, ref_fid)
        p["formid"] = f"{pkg_fids[edid]:08X}"

    def form_fid(name: str) -> int:
        return GOLD001 if name == "Gold001" else w.fid(name)

    for edid, d in lay["npcs"].items():
        _npc(w, edid, d, class_fid, pkg_fids, form_fid)
        d["formid"] = f"{w.fid(edid):08X}"
    # fill in the refs
    for key, c in lay["cells"].items():
        for i, ref in enumerate(c["refs"]):
            r = ref_recs[(key, i)]
            base = ref["base"]
            if base.startswith("npc:"):
                base_fid = w.fid(base[4:])
            elif base == "marker":
                base_fid = XMARKER_HEADING
            else:
                base_fid = w.fid(KIT[base]["edid"])
            r.add("NAME", u32(base_fid))
            if ref.get("teleport"):
                t = ref["teleport"]
                r.add("XTEL", struct.pack("<I6f", w.fid(t["to"]), *t["pos"], 0.0, 0.0, t["rot"]))
            x, y, z = ref["pos"]
            r.add("DATA", pos(x, y, z, 0.0, 0.0, ref["rot"]))
    for key, k in KIT.items():
        lay["kit"][key]["formid"] = f"{w.fid(k['edid']):08X}"
    for key, c in lay["cells"].items():
        c["formid"] = f"{w.fid(c['edid']):08X}"
    return w.build(), lay


def write(out_dir: Path) -> tuple[Path, Path]:
    """Write ForgeTestCells.esp + ForgeTestCells.layout.json into out_dir."""
    data, lay = build_plugin()
    out_dir.mkdir(parents=True, exist_ok=True)
    esp = out_dir / PLUGIN_NAME
    esp.write_bytes(data)
    lj = out_dir / "ForgeTestCells.layout.json"
    lj.write_text(json.dumps(lay, indent=1, sort_keys=True), encoding="utf-8")
    return esp, lj


def cell_key(name: str | None) -> str:
    """Map a test_plan cell name (arena/street/open or the cell EditorID) to a key."""
    if not name:
        return DEFAULT_CELL
    n = str(name).strip().lower()
    for key, c in CELLS.items():
        if n in (key, c["edid"].lower()):
            return key
    aliases = {"combat": "arena", "spells": "arena", "town": "street", "city": "street", "merchant": "street",
               "doors": "street", "exterior": "open", "weather": "open", "projectiles": "open"}
    if n in aliases:
        return aliases[n]
    raise ValueError(f"unknown test cell {name!r}; use one of {sorted(CELLS)}")


# ---------------------------------------------------------------- mesh kit (assetkit)
def build_kit(out_data: Path) -> list[Path]:
    """Generate the kit NIFs + textures under out_data (a Data-shaped folder). Needs numpy + Pillow."""
    from assetkit import mesh as M, nif as N, nifbuild as NB, texture as T

    files = []
    mats = {"stone": ("stone", "#8d8a83", 7), "wood": ("wood", "#7a5a3a", 11)}
    for name, (kind, color, seed) in mats.items():
        try:
            layer = T.material(kind, (256, 256), color, seed)
        except (KeyError, ValueError):
            layer = T.material("stone", (256, 256), color, seed)
        base = out_data / "textures" / KIT_TEX_DIR.replace("\\", "/") / name
        T.save_textures(layer, base, preview_png=False)
        files += [base.with_suffix(".dds"), base.parent / (base.name + "_n.dds")]
    for key, k in KIT.items():
        sx, sy, sz = k["size"]
        m = M.box(sx, sy, sz, name=key)
        m.translate(0, 0, -sz / 2 if k["origin"] == "top" else sz / 2)
        m.uv = m.uv * max(1.0, max(sx, sy, sz) / 256.0)       # tile the 256 px texture every 256 units
        tex = f"textures\\{KIT_TEX_DIR}\\{k['texture']}.dds"
        nif = NB.build(m, tex, name=k["edid"], profile="clutter" if key == "trinket" else "static",
                       prn=None, mass=0.5, havok_material="stone" if k["texture"] == "stone" else "wood",
                       glossiness=10.0)
        p = out_data / "meshes" / KIT_MESH_DIR.replace("\\", "/") / f"{key}.nif"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(N.write(nif))
        files.append(p)
    return files
